# Generated by Django 3.1.2 on 2020-12-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='number_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_app.users')),
            ],
        ),
    ]
