# Generated by Django 3.1.2 on 2021-02-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0003_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('Elève', 'Elève'), ('Enseignant', 'Enseignant')], max_length=15),
        ),
    ]
